@baseUrl = http://localhost:8080/Plone

###

get {{baseUrl}}/events/aggregator

###

get {{baseUrl}}/events/termin-1

###

get {{baseUrl}}/produkte


###

get {{baseUrl}}/produkte/neue-produkte/unseren-neuen-produkte?expand=contextnavigation


###

get {{baseUrl}}/@vocabularies
Authorization: Basic admin:admin

###

